name: Windows RDP

on:
workflow_dispatch:

jobs:
build:
runs-on: windows-latest
timeout-minutes: 360

```
steps:
- name: Enable Remote Desktop
  run: |
    Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
    Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

- name: Set Password
  run: |
    net user runneradmin P@ssw0rd!

- name: Install ngrok
  run: |
    choco install ngrok -y

- name: Authenticate ngrok
  run: |
    ngrok config add-authtoken $Env:NGROK_AUTH_TOKEN
  env:
    NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

- name: Start Tunnel
  run: |
    Start-Process ngrok -ArgumentList "tcp 3389"
    Start-Sleep -Seconds 10
    Invoke-RestMethod http://127.0.0.1:4040/api/tunnels
